### ISSUE TITLE
Rate limiting

### ISSUE THREAD

**Issue by akersten** [Ricky54326/EmailTemplater#8]
Just a thought. Check out [gmail's usage limits](https://developers.google.com/gmail/api/v1/reference/quota) document - you won't want to be sending out more than 5 emails every 2 seconds (100 quota units per send, 250 quota unit limit per second). The confirm screen kind-of-sort-of acts as a rate limiter, but if someone gets too trigger happy on hitting 'y' then you might get 429'd by gmail. Consider adding a cooldown timer of 500ms per email.

**Comment by WowSuchRicky** [comment]
Hey Alex,

Thanks for the tip. We would have had this issue, but we're actually having the script runner manually confirm Y/N per each email (as you saw) before they're being sent out. I think even if someone were pressing Y repeatedly, we wouldn't hit this limit hopefully. If we ever remove the manual confirmation step, we'll definitely add rate limiting, and we'll play around with this a bit too. If people are having issues w/ rate limiting, we'll add it in last second.

**Comment by akersten** [comment]
Cool! Just making sure it was something y'all were aware of.

**Comment by austinhartzheim** [comment]
Thanks Alex.

I looked into this too. From my experience sending the emails, the time taken to actually authenticate to the SMTP server and send the email each time is probably enough of a delay. I haven't checked if it is possible for SMTP to maintain the connection (although, I suspect it is).

If the human reviewer is actually doing what they are supposed to (i.e., checking for mistakes), we shouldn't ever reach this limit. But, it still might be worth putting something in, especially if we decide to maintain the SMTP connection in the future.
